// Generated by Wrangler on Tue Aug 13 2024 00:30:59 GMT+0800 (香港标准时间)
// by running `wrangler types`

interface Env {
  DB: D1Database;
  KV: KVNamespace;
  SESSION: KVNamespace;
  APP_URL?: string;
}

declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    KV: KVNamespace;
    SESSION: KVNamespace;
    APP_URL?: string;
  }
}
